### ISSUE TITLE
SDK calc_close_* not discounting zombie interest

### ISSUE THREAD

**Issue by slundqui** [delvtech/hyperdrive-rs#197] opened 2024-09-13 16:57 UTC
There's a bug where calling rust's `calc_close_long` or `calc_close_short` when calculating the unrealized value of matured, but not closed, positions. Since the rust functions under the hood returns shares, agent0 converts it back to base using the current vault share price. This is correct when the position isn't matured, but since hyperdrive auto closes matured positions via checkpointing, we should be using the vault share price of when the position matured to convert from shares to base.

This issue is exacerbated when a user asks for shares back when closing (in the case of e.g., steth, where agent0 makes trades using yield), as there is a difference between the shares gotten from rust and the actual shares returned when closed due to the same issue. Here, the solution is:

```
user_return_in_shares = rust_shares_returned * maturity_share_price / current_share_price
```

**Comment by dpaiton** [comment] 2024-09-24 16:09
Updated test in the PR. I changed `just_after_maturity = state.position_duration() + state.checkpoint_duration()` which should fully cover any combination of those two values. The earlier test is now failing:
```
User lost money holding the long: earnings_before=FixedPoint(16384052.613607627475940513) > earnings_after=FixedPoint(16158949.286573306770097460)
```

**Comment by dpaiton** [comment] 2024-09-24 17:15
I confirmed, @MazyGio -- the fees account for the discrepancy. I simplified the test to only look at proceeds after maturity & added a short one.

The tests in #196 demonstrate that the problem is not an issue. Closing when that PR merges.

**Closed** 2024-10-02 00:40 UTC
Labels: bug
